#!/bin/sh

# Run this script to create symbolic links for every header of ClasTool
# libraries inside the "include" directory.
#
# Now you can use the "include" directory in your Makefiles and compile classes
# that include ClasTool headers.

MODULES='ClasBanks TClasTool VirtualReader DSTReader FillBank PartSieve MapUtils Filter'

mkdir -p include
cd include

for i in $MODULES
do
    for j in ../$i/*.h
    do
        ln -s -f $j
    done
done

rm *LinkDef.h
cd ..
