// Source File TFBPMClass.cc
// Autogenerated
// Author: G.Gavalian (ODU) 2009
#include "TFBPMClass.h"
ClassImp(TFBPMClass)

TFBPMClass::TFBPMClass ( TFBPMClass *Tmp){
 ID  = Tmp->ID;
 TDC  = Tmp->TDC;
 ADC  = Tmp->ADC;
}

void TFBPMClass::Print() {  }
