// Header File TFBPMClass.h
// Autogenerated
// Author: G.Gavalian (ODU) 2009
#ifndef _TFBPMClass_
#define _TFBPMClass_
#include <iostream>

using namespace std;

#include "TObject.h"
#include "TString.h"

class TFBPMClass : public TObject{
public:

Int_t  ID;
Int_t  TDC;
Int_t  ADC;

 public:

TFBPMClass () {};
TFBPMClass ( TFBPMClass *Tmp);
virtual ~TFBPMClass () {};
void Print();

ClassDef(TFBPMClass,1)
};

#endif
