// Header File TICHBClass.h
// Autogenerated
// Author: G.Gavalian (ODU) 2009
#ifndef _TICHBClass_
#define _TICHBClass_
#include <iostream>

using namespace std;

#include "TObject.h"
#include "TString.h"

class TICHBClass : public TObject{
public:

Float_t  Eclust;
Float_t  Eclmax;
Float_t  Tclust;
Float_t  T_next;
Float_t  xclust;
Float_t  yclust;
Float_t  zclust;
Float_t  xclmax;
Float_t  yclmax;
Float_t  M2_x;
Float_t  M2_y;
Float_t  M3_x;
Float_t  M3_y;
Int_t  ncryst;

 public:

TICHBClass () {};
TICHBClass ( TICHBClass *Tmp);
virtual ~TICHBClass () {};
void Print();

ClassDef(TICHBClass,1)
};

#endif
