// Source File TICHBClass.cc
// Autogenerated
// Author: G.Gavalian (ODU) 2009
#include "TICHBClass.h"
ClassImp(TICHBClass)

TICHBClass::TICHBClass ( TICHBClass *Tmp){
 Eclust  = Tmp->Eclust;
 Eclmax  = Tmp->Eclmax;
 Tclust  = Tmp->Tclust;
 T_next  = Tmp->T_next;
 xclust  = Tmp->xclust;
 yclust  = Tmp->yclust;
 zclust  = Tmp->zclust;
 xclmax  = Tmp->xclmax;
 yclmax  = Tmp->yclmax;
 M2_x  = Tmp->M2_x;
 M2_y  = Tmp->M2_y;
 M3_x  = Tmp->M3_x;
 M3_y  = Tmp->M3_y;
 ncryst  = Tmp->ncryst;
}

void TICHBClass::Print() {  }
