// Source File TFBPMClass.cc
// Autogenerated
// Author: G.Gavalian (ODU) 2009
#include "TROOT.h"
#include "TFBPMClass.h"
#include "clasbanks.h"
void  Fill_FBPM_Bank(TFBPMClass *gcFBPM,FBPM *pFBPM , int nrow);
void  Fill_FBPM_Bank(TFBPMClass *gcFBPM,FBPM *pFBPM , int nrow)
{
 gcFBPM->ID  = pFBPM->get_ID(nrow);
 gcFBPM->TDC  = pFBPM->get_TDC(nrow);
 gcFBPM->ADC  = pFBPM->get_ADC(nrow);
}

// End of Fill File -----------------

