// Source File TICHBClass.cc
// Autogenerated
// Author: G.Gavalian (ODU) 2009
#include "TROOT.h"
#include "TICHBClass.h"
#include "clasbanks.h"
void  Fill_ICHB_Bank(TICHBClass *gcICHB,ICHB *pICHB , int nrow);
void  Fill_ICHB_Bank(TICHBClass *gcICHB,ICHB *pICHB , int nrow)
{
 gcICHB->Eclust  = pICHB->get_Eclust(nrow);
 gcICHB->Eclmax  = pICHB->get_Eclmax(nrow);
 gcICHB->Tclust  = pICHB->get_Tclust(nrow);
 gcICHB->T_next  = pICHB->get_T_next(nrow);
 gcICHB->xclust  = pICHB->get_xclust(nrow);
 gcICHB->yclust  = pICHB->get_yclust(nrow);
 gcICHB->zclust  = pICHB->get_zclust(nrow);
 gcICHB->xclmax  = pICHB->get_xclmax(nrow);
 gcICHB->yclmax  = pICHB->get_yclmax(nrow);
 gcICHB->M2_x  = pICHB->get_M2_x(nrow);
 gcICHB->M2_y  = pICHB->get_M2_y(nrow);
 gcICHB->M3_x  = pICHB->get_M3_x(nrow);
 gcICHB->M3_y  = pICHB->get_M3_y(nrow);
 gcICHB->ncryst  = pICHB->get_ncryst(nrow);
}

// End of Fill File -----------------

